name: kv_preferences
description: Type-safe key-value storage over SharedPreferences with migration support.
version: 1.0.0
publish_to: https://github.com/4uzhoy/kv_preferences
repository: https://github.com/4uzhoy/kv_preferences
issue_tracker: https://github.com/4uzhoy/kv_preferences/issues
homepage: https://github.com/4uzhoy/kv_preferences

environment:
  sdk: ^3.7.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
